-- Fresh empty database only. Generated from the EF Core 8.0.10 model.
BEGIN;
CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "DisplayName" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE "Projects" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "OwnerId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Labels" (
    "Id" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    "Name" text NOT NULL,
    "ColorHex" text NOT NULL,
    CONSTRAINT "PK_Labels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Labels_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ProjectMembers" (
    "Id" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Role" integer NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProjectMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProjectMembers_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Sprints" (
    "Id" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Goal" text,
    "StartDate" date NOT NULL,
    "EndDate" date NOT NULL,
    "Status" integer NOT NULL,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_Sprints" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sprints_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);


CREATE TABLE "TaskItems" (
    "Id" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Status" integer NOT NULL,
    "Priority" integer NOT NULL,
    "Order" integer NOT NULL,
    "SprintId" uuid,
    "IssueType" integer NOT NULL,
    "StoryPoints" integer,
    "DueDate" date,
    "AssigneeId" uuid,
    "CreatedById" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_TaskItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskItems_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskItems_Sprints_SprintId" FOREIGN KEY ("SprintId") REFERENCES "Sprints" ("Id") ON DELETE SET NULL
);


CREATE TABLE "Attachments" (
    "Id" uuid NOT NULL,
    "TaskItemId" uuid NOT NULL,
    "FileName" text NOT NULL,
    "StoragePath" text NOT NULL,
    "ContentType" text NOT NULL,
    "FileSizeBytes" bigint NOT NULL,
    "UploadedById" uuid NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Attachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Attachments_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Comments" (
    "Id" uuid NOT NULL,
    "TaskItemId" uuid NOT NULL,
    "AuthorId" uuid NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE
);


CREATE TABLE "TaskLabels" (
    "TaskItemId" uuid NOT NULL,
    "LabelId" uuid NOT NULL,
    CONSTRAINT "PK_TaskLabels" PRIMARY KEY ("TaskItemId", "LabelId"),
    CONSTRAINT "FK_TaskLabels_Labels_LabelId" FOREIGN KEY ("LabelId") REFERENCES "Labels" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskLabels_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE INDEX "IX_Attachments_TaskItemId" ON "Attachments" ("TaskItemId");


CREATE INDEX "IX_Comments_TaskItemId" ON "Comments" ("TaskItemId");


CREATE UNIQUE INDEX "IX_Labels_ProjectId_Name" ON "Labels" ("ProjectId", "Name");


CREATE UNIQUE INDEX "IX_ProjectMembers_ProjectId_UserId" ON "ProjectMembers" ("ProjectId", "UserId");


CREATE INDEX "IX_Projects_OwnerId" ON "Projects" ("OwnerId");


CREATE UNIQUE INDEX "IX_Sprints_ProjectId" ON "Sprints" ("ProjectId") WHERE "Status" = 1;


CREATE INDEX "IX_TaskItems_ProjectId_Status" ON "TaskItems" ("ProjectId", "Status");


CREATE INDEX "IX_TaskItems_SprintId" ON "TaskItems" ("SprintId");


CREATE INDEX "IX_TaskLabels_LabelId" ON "TaskLabels" ("LabelId");



COMMIT;
